version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: banquerupt-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banquerupt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

  # Express Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: banquerupt-backend
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=banquerupt
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=votre_secret_jwt_ultra_securise_a_changer_en_production
      - COOKIE_SECRET=un_autre_secret_pour_les_cookies
      - PORT=5000
    ports:
      - "5000:5000"
    restart: unless-stopped

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: banquerupt-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  postgres_data: